//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: Foo.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComTestFoo")
#ifdef RESTRICT_ComTestFoo
#define INCLUDE_ALL_ComTestFoo 0
#else
#define INCLUDE_ALL_ComTestFoo 1
#endif
#undef RESTRICT_ComTestFoo

#if !defined (ComTestFoo_) && (INCLUDE_ALL_ComTestFoo || defined(INCLUDE_ComTestFoo))
#define ComTestFoo_

#define RESTRICT_ComTestFooInterface 1
#define INCLUDE_ComTestFooInterface 1
#include "FooInterface.h"

@interface ComTestFoo : NSObject < ComTestFooInterface > {
 @public
  jint myInt_;
}

#pragma mark Public

- (instancetype)init;

- (jint)add2WithInt:(jint)firstparam
            withInt:(jint)secondparam;

- (jint)fibWithInt:(jint)x;

- (jint)getMyInt;

+ (jint)getMyStaticInt;

- (jint)return100;

+ (jint)return100Static;

- (jint)returnNumWithInt:(jint)x;

- (NSString *)returnStringWithNSString:(NSString *)s;

- (void)setMyIntWithInt:(jint)x;

+ (void)setMyStaticIntWithInt:(jint)x;

- (jint)testKotlinInterfaceWithComTestFooInterface:(id<ComTestFooInterface>)i
                                           withInt:(jint)num;

@end

J2OBJC_EMPTY_STATIC_INIT(ComTestFoo)

inline jint ComTestFoo_get_myStaticInt(void);
inline jint ComTestFoo_set_myStaticInt(jint value);
inline jint *ComTestFoo_getRef_myStaticInt(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT jint ComTestFoo_myStaticInt;
J2OBJC_STATIC_FIELD_PRIMITIVE(ComTestFoo, myStaticInt, jint)

FOUNDATION_EXPORT void ComTestFoo_init(ComTestFoo *self);

FOUNDATION_EXPORT ComTestFoo *new_ComTestFoo_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComTestFoo *create_ComTestFoo_init(void);

FOUNDATION_EXPORT void ComTestFoo_setMyStaticIntWithInt_(jint x);

FOUNDATION_EXPORT jint ComTestFoo_getMyStaticInt(void);

FOUNDATION_EXPORT jint ComTestFoo_return100Static(void);

J2OBJC_TYPE_LITERAL_HEADER(ComTestFoo)

#endif

#if !defined (ComTestFoo_InnerClass_) && (INCLUDE_ALL_ComTestFoo || defined(INCLUDE_ComTestFoo_InnerClass))
#define ComTestFoo_InnerClass_

@class ComTestFoo;

@interface ComTestFoo_InnerClass : NSObject

#pragma mark Package-Private

- (instancetype)initWithComTestFoo:(ComTestFoo *)outer$;

- (jdouble)myInnerFuncWithDouble:(jdouble)a
                      withDouble:(jdouble)b;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComTestFoo_InnerClass)

FOUNDATION_EXPORT void ComTestFoo_InnerClass_initWithComTestFoo_(ComTestFoo_InnerClass *self, ComTestFoo *outer$);

FOUNDATION_EXPORT ComTestFoo_InnerClass *new_ComTestFoo_InnerClass_initWithComTestFoo_(ComTestFoo *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComTestFoo_InnerClass *create_ComTestFoo_InnerClass_initWithComTestFoo_(ComTestFoo *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ComTestFoo_InnerClass)

#endif

#if !defined (ComTestFoo_NestedClass_) && (INCLUDE_ALL_ComTestFoo || defined(INCLUDE_ComTestFoo_NestedClass))
#define ComTestFoo_NestedClass_

@interface ComTestFoo_NestedClass : NSObject

#pragma mark Package-Private

- (instancetype)init;

- (jdouble)myNestedFuncWithDouble:(jdouble)a
                       withDouble:(jdouble)b;

@end

J2OBJC_EMPTY_STATIC_INIT(ComTestFoo_NestedClass)

FOUNDATION_EXPORT void ComTestFoo_NestedClass_init(ComTestFoo_NestedClass *self);

FOUNDATION_EXPORT ComTestFoo_NestedClass *new_ComTestFoo_NestedClass_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComTestFoo_NestedClass *create_ComTestFoo_NestedClass_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ComTestFoo_NestedClass)

#endif

#pragma pop_macro("INCLUDE_ALL_ComTestFoo")
