//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: FooInterface.java
//

#include "J2ObjC_source.h"
#include "FooInterface.h"

@interface ComTestFooInterface : NSObject

@end

@implementation ComTestFooInterface

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "I", 0x401, 0, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(fibWithInt:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "fib", "I" };
  static const J2ObjcClassInfo _ComTestFooInterface = { "FooInterface", "com.test", ptrTable, methods, NULL, 7, 0x609, 1, 0, -1, -1, -1, -1, -1 };
  return &_ComTestFooInterface;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ComTestFooInterface)
