//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: FooInterface.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComTestFooInterface")
#ifdef RESTRICT_ComTestFooInterface
#define INCLUDE_ALL_ComTestFooInterface 0
#else
#define INCLUDE_ALL_ComTestFooInterface 1
#endif
#undef RESTRICT_ComTestFooInterface

#if !defined (ComTestFooInterface_) && (INCLUDE_ALL_ComTestFooInterface || defined(INCLUDE_ComTestFooInterface))
#define ComTestFooInterface_

@protocol ComTestFooInterface < JavaObject >

- (jint)fibWithInt:(jint)n;

@end

J2OBJC_EMPTY_STATIC_INIT(ComTestFooInterface)

J2OBJC_TYPE_LITERAL_HEADER(ComTestFooInterface)

#endif

#pragma pop_macro("INCLUDE_ALL_ComTestFooInterface")
